# Due to rate limiting from gnu.org
accept = [429]

cache = true
exclude = [
  '^http://www\.gnu\.org',
  '^https://www\.gnu\.org',
  '^https://www\.ovh\.com/auth/api/createToken',
]
exclude_path = [
  ".cache/",
  ".direnv/",
  ".flatpak/",
  ".flatpak-builder/",
  "build.*/",
  "repo/",
]
max_cache_age = "2w"
