name: Update Go module

"on":
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-go-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Update the Caddy OVH Go module
        run: nix run '.#update-go-module'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          assignees: ${{ github.repository_owner }}
          branch: "update/go-module"
          commit-message: "chore(deps): Update the Caddy OVH Go module"
          title: "chore(deps): Update the Caddy OVH Go module"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
